# https://docs.docker.com/compose/compose-file/
name: jukebot

services:
    db:
        image: postgres

        ports:
            - ${DB_PORT}

        volumes:
            - data:/data/db

        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}

volumes:
    data: {}
