# https://docs.docker.com/compose/compose-file/
name: jukebot

services:
    # cobalt (https://github.com/imputnet/cobalt/blob/main/docs/run-an-instance.md)
    cobalt-api:
        image: ghcr.io/imputnet/cobalt:10

        init: true
        read_only: true
        restart: unless-stopped
        container_name: cobalt-api

        ports:
            - 9000:9000/tcp

        environment:
            API_URL: 'http:/localhost:9000/'
            TUNNEL_LIFESPAN: 14400
            DURATION_LIMIT: 14400

        labels:
            - com.centurylinklabs.watchtower.scope=cobalt

    # Watchtower (automatic cobalt image updates)
    watchtower:
        image: ghcr.io/containrrr/watchtower
        restart: unless-stopped
        command: --cleanup --scope cobalt --interval 900 --include-restarting
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    # Jukebot
    discord-bot:
        build: .
        restart: on-failure:3
