name: Deploy

on:
    workflow_run:
        workflows: [CI]
        types: [completed]
        branches: [main]

concurrency:
    group: bot-deploy
    cancel-in-progress: true

jobs:
    deploy:
        name: Deploy to Production
        if: github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest
        timeout-minutes: 2

        steps:
            - name: Execute remote build process
              uses: appleboy/ssh-action@v1.2.2
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd services_v2/Jukebot
                      git reset --hard --quiet
                      git clean -d --force --quiet
                      git pull --quiet
                      docker compose up --build --detach
